spring:
  config:
    activate:
      on-profile: prod

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://beotkkotthon-dev.cwsu2gsusmej.ap-northeast-2.rds.amazonaws.com:3306/beotkkot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: beotkkot15!

## JWT Setting
jwt:
  secret: c3ByaW5nLWJhY2tlbmQtYmVvdGtrb3R0aG9uLW5ld3NsZXR0ZXItcHJvamVjdC1zZWN1cml0eS1qd3Qtc2VjcmV0LWtleXl5Cg==

# aws
cloud:
  aws:
    credentials:
      accessKey: AKIA4TBH5MFOAQDVBEP7
      secretKey: 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
    s3:
      bucket: beotkkotthon-s3
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false